### ISSUE TITLE
Base as a class/module name

### ISSUE THREAD

**Issue by jgaskins** [dhruvrajvanshi/Moonshine#18]
`Base` as a class or module name (such as `Moonshine::Controllers::Base`) is one of many Rails conventions I don't believe should be copied. It is problematic because although it is indeed an abstract base class, that's an implementation detail. Since it doesn't define behavior for a military installation or a baseball position (an actual base ;-)), maybe it should just instead be `Moonshine::Controller`.

**Comment by dhruvrajvanshi** [comment]
I think I'll alias this and Moonshine::App too. Less typing is helpful.
As far as naming convention is concerned, think of Base as a synonym for Core. Controller unfortunately landed up in Base. I am not that familiar with Rails so the similarity is coincidental.

**Comment by dhruvrajvanshi** [comment]
Check the change log

**Comment by jgaskins** [comment]
:+1:
