### ISSUE TITLE
Charset

### ISSUE THREAD

**Issue by nik736** [dhruvrajvanshi/Moonshine#22]
Hi,
is it possible to set a charset header?

**Comment by dhruvrajvanshi** [comment]
You can set do response.headers["Content-type"] = "whatever;charset=utf-8".
If you need to set it on a global level, you can create middleware that can set the header for every outgoing response.

**Comment by dhruvrajvanshi** [comment]
Did I answer your question? Can I close this now?

**Comment by nik736** [comment]
Yep, sure, sorry and thanks.
