### ISSUE TITLE
Crystal vs Iron

### ISSUE THREAD

**Issue by 5nyper** [dhruvrajvanshi/Moonshine#7]
https://gist.github.com/Vikaton/3102c16ee14ef3d76244

what boredom leads too

**Comment by mrtryhard** [comment]
Interesting, how is Iron completeness / maturity compared to moonshine? 

But number are nice :^)

**Comment by 5nyper** [comment]
I personally don't know: http://github.com/Iron/Iron

**Comment by mrtryhard** [comment]
By the looks;  
- 85+22 issues (85 closed). 
- 32 contributors
- 330+ pull requests. 

My guess is that they have more overhead and probably features. Yes, Moonshine is fast along with Crystal, but I do believe it might be early to compare those two yet :-) .  

But numbers are still interesting, and thanks for this small benchmark.

**Comment by 5nyper** [comment]
No problem, though I dont think they have overhead, since They're lib is divided into seperate other libs that you need to import by themselves, so they make it stay minimal, but yeah, we'll see where this goes :P

**Comment by mrtryhard** [comment]
Ahah, but I mostly meant overall code execution, but yea, I'm pretty sure this can go far :-)

**Comment by 5nyper** [comment]
swag
